### ISSUE TITLE
Feature request: generate multiple types in single file

### ISSUE THREAD

**Issue by Antonboom** [moznion/gonstructor#10]
```
gonstructor -types=A,B,C,D -output types.gen.go
```

**Comment by moznion** [comment]
Thank you for your request, @Antonboom.
I implemented that feature at #14, what do you think about that?

**Comment by moznion** [comment]
Implemented by #14

**Comment by moznion** [comment]
The version [v0.4.0])https://github.com/moznion/gonstructor/releases/tag/v0.4.0) that contains this feature has been published.
