### ISSUE TITLE
add support for embedding

### ISSUE THREAD

**Issue by moznion** [moznion/gonstructor#5]
@kovetskiy 
02ca4b74feb987d386cdbe547ba835ed382c87db
This commit has made CI failed, so I reverted that commit and removed the tagged version `v0.3.0`.

Could you please send a pull-request instead of pushing commits to the master branch?

**Comment by moznion** [comment]
ref: https://github.com/moznion/gonstructor/runs/1827883082?check_suite_focus=true

**Comment by kovetskiy** [comment]
Oops, here it is #6

**Comment by moznion** [comment]
@kovetskiy
I appreciate your contribution!
I've published the new version `v0.3.1`: https://github.com/moznion/gonstructor/releases/tag/v0.3.1
