### ISSUE TITLE
Please upgrade go version and deps

### ISSUE THREAD

**Issue by Antonboom** [moznion/gonstructor#9]
Hello!

When I have tried the tool, I was faced with issue:
https://github.com/golang/go/issues/37617

I did fork and 
- moved to Go 1.19
- `go get -u ./...`
- `go install ./cmd/gonstructor/...`

And after it works fine.

**Comment by moznion** [comment]
The version [v0.4.0])https://github.com/moznion/gonstructor/releases/tag/v0.4.0) that contains this feature has been published.
